language: go
go:
  - 1.8.5
  - 1.9.2
sudo: false
install:
  - go get -v github.com/lightningnetwork/lightning-onion
  - go get -v github.com/davecgh/go-spew/spew
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go test -v
